version: '3.3'

services:
    app:
        restart: always
        build: .
        image: network_app_server
        container_name: network_app_server
        network_mode: "host"
        env_file:
          - .env
        environment:
          - OPENAI_API_KEY=${OPENAI_API_KEY}
        expose:
            - 8602
